name: Elixir CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.x
            otp: 24.2.x
            warnings_as_errors: true
            static_analysis: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: os-${{ runner.os }}-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix credo --strict
      - run: mix test
      - run: mix dialyzer --halt-exit-status
        if: matrix.static_analysis
